### ISSUE TITLE
Draw conditions

### ISSUE THREAD

**Issue by GasiorMateusz** [Kacper-Mila/Team2_Polish_draughts#27]
conditions ending game with draw result:

- [x] both player's movement is not possible. If (one player can't move then the other is winner
- [x] if there are two crowns left only
- [x] if there one player chooses the same position on the board 3 times
- [x] wiki: Jeśli żaden gracz nie jest w stanie tego osiągnąć (każdy gracz wykona po 15 ruchów damkami bez zmniejszania liczby pionków pozostających na planszy), następuje remis.

**Comment by kattommy** [comment]
the opponent's movement is not possible

**Comment by GasiorMateusz** [comment]
trzeba dopracowac te warunki. Są one załączone w gałęzi "test_draw_condition"
